server:
  port: 80


spring:
  redis:
    database: 0
    host: 192.168.43.117
    port: 7000
    password: lbr
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

